# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Kevin Meyvaert
tagline: photographer based in gent, belgium. personal work on film. full stack engineer.
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Kevin Meyvaert - photographer based in Gent, Belgium. Personal work on film.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kevinmeyvaert.be" # the base hostname & protocol for your site

# Navigation
navigation:
  - name: articles
    url: /articles
  - name: records i want
    url: /wantlist
  - name: behangmotief.com
    url: https://behangmotief.com
  - name: i like running
    url: https://www.strava.com/athletes/37171291

# Social Links
social:
  instagram: https://www.instagram.com/kevinmeyvaert/
  email: kevin.meyvaert@gmail.com
  spotify: https://open.spotify.com/user/kevinmeyvaert

# Build settings
# theme: minima  # Disabled - using custom layouts
plugins:
  - jekyll-feed
  - jekyll_picture_tag
  - jekyll-paginate

# Pagination settings
paginate: 10
paginate_path: "/page/:num/"

# Jekyll Picture Tag Configuration
picture:
  source: "assets/images"
  output: "assets/generated"
  markup: "picture"
  formats: [avif, webp, original]
  dimension_attributes: true
  fast_build: development
  nomarkdown: false

# Collections
collections:
  articles:
    output: true
    permalink: /articles/:title/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
